export const dataDB = [
    {
        id: 1,
        name: "polo 1",
        urlImages: "./images/home.png",
        stock: 5,
        price: 2000,
    },
    {
        id: 2,
        name: "capucha 1",
        urlImages: "./images/featured1.png",
        stock: 7,
        price: 4000,
    },
    {
        id: 3,
        name: "polo 2",
        urlImages: "./images/featured2.png",
        stock: 7,
        price: 4500,
    },
    {
        id: 4,
        name: "capucha 2",
        urlImages: "./images/featured3.png",
        stock: 7,
        price: 4500,
    },
    {
        id: 5,
        name: "pantalones",
        urlImages: "./images/pants.jpg",
        stock: 4,
        price: 5000,
    },
    {
        id: 6,
        name: "zapatos",
        urlImages: "./images/zapato.jpg",
        stock: 10,
        price: 6000,
    },
    {
        id: 7,
        name: "nuevo",
        urlImages: "./images/new.jpg",
        stock: 10,
        price: 8300,
    },
    {
        id: 8,
        name: "blusa",
        urlImages: "./images/blusa.jpg",
        stock: 3,
        price: 3500,
    },
    {
        id: 9,
        name: "vestido",
        urlImages: "./images/vestido.jpg",
        stock: 9,
        price: 9000,
    },
];
